# Generated by Django 4.2.20 on 2025-06-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='user_profile.userprofile')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_written', to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('writer', 'owner')},
            },
        ),
    ]
